rm Genarris.* j_*.out
#rm -r aims_target1_2mpc_he harris_single_molecule_prep_aims_dir structure_dir_for_harris_single_molecule_prep target1_2mpc_he
#rm -r aims_relaxation_single structure_dir_for_relaxing_single_molecule
rm -r aims_target1_2mpc_he
